FROM aarch64/debian:jessie

MAINTAINER datarhei <info@datarhei.org>

ENV RESTREAMER_EDGE_VERSION=0.1.0-rc.3 \
    FFMPEG_VERSION=2.8.6 \
    YASM_VERSION=1.3.0 \
    LAME_VERSION=3_99_5 \
    NGINX_VERSION=1.9.9 \
    NGINX_RTMP_VERSION=1.1.7.10 \

    SRC="/usr/local" \
    LD_LIBRARY_PATH="${SRC}/lib" \
    PKG_CONFIG_PATH="${SRC}/lib/pkgconfig" \

    BUILDDEPS="autoconf automake gcc g++ libtool make nasm unzip zlib1g-dev libssl-dev xz-utils cmake build-essential libpcre3-dev"

RUN rm -rf /var/lib/apt/lists/* && \
    apt-get update --fix-missing && \
    apt-get install -y --force-yes curl git libpcre3 tar perl ca-certificates apache2-utils libaio1 libxml2 libxslt-dev ${BUILDDEPS} && \

    # yasm
    DIR="$(mktemp -d)" && cd "${DIR}" && \
    curl -LOks "https://www.tortall.net/projects/yasm/releases/yasm-${YASM_VERSION}.tar.gz" && \
    tar xzvf "yasm-${YASM_VERSION}.tar.gz" && \
    cd "yasm-${YASM_VERSION}" && \
    cp /usr/share/automake-1.14/config.guess config.guess && \
    ./configure \
        --prefix="${SRC}" \
        --bindir="${SRC}/bin" && \
    make -j"$(nproc)" && \
    make install && \
    make distclean && \
    rm -rf "${DIR}" && \

    # x264
    DIR="$(mktemp -d)" && cd "${DIR}" && \
    git clone --depth 1 "git://git.videolan.org/x264" && \
    cd x264 && \
    ./configure \
        --prefix="${SRC}" \
        --bindir="${SRC}/bin" \
        --enable-static \
        --disable-cli && \
    make -j"$(nproc)" && \
    make install && \
    make distclean && \
    rm -rf "${DIR}" && \

    # libmp3lame
    DIR="$(mktemp -d)" && cd "${DIR}" && \
    curl -LOks "https://github.com/rbrito/lame/archive/RELEASE__${LAME_VERSION}.tar.gz" && \
    tar xzvf "RELEASE__${LAME_VERSION}.tar.gz" && \
    cd "lame-RELEASE__${LAME_VERSION}" && \
    cp /usr/share/automake-1.14/config.guess config.guess && \
    ./configure \
        --prefix="${SRC}" \
        --bindir="${SRC}/bin" \
        --enable-nasm \
        --disable-shared && \
    make -j"$(nproc)" && \
    make install && \
    make distclean && \
    rm -rf "${DIR}" && \

    # ffmpeg
    # patch: andrew-shulgin Ignore invalid sprop-parameter-sets missing PPS
    DIR="$(mktemp -d)" && cd "${DIR}" && \
    curl -LOks "https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz" && \
    tar xzvf "ffmpeg-${FFMPEG_VERSION}.tar.gz" && \
    cd "ffmpeg-${FFMPEG_VERSION}" && \
    curl -Lks "https://github.com/FFmpeg/FFmpeg/commit/1c7e2cf9d33968375ee4025d2279c937e147dae2.patch" | patch -p1 && \
    ./configure \
        --prefix="${SRC}" \
        --bindir="${SRC}/bin" \
        --extra-cflags="-I${SRC}/include" \
        --extra-ldflags="-L${SRC}/lib" \
        --extra-libs=-ldl \
        --enable-nonfree \
        --enable-gpl \
        --enable-version3 \
        --enable-avresample \
        --enable-libmp3lame \
        --enable-libx264 \
        --enable-openssl \
        --enable-postproc \
        --enable-small \
        --disable-debug \
        --disable-doc \
        --disable-ffserver && \
    make -j"$(nproc)" && \
    make install && \
    make distclean && \
    hash -r && \
    cd tools && \
    make qt-faststart && \
    cp qt-faststart "${SRC}/bin" && \
    rm -rf "${DIR}" && \
    echo "${SRC}/lib" > "/etc/ld.so.conf.d/libc.conf" && \
    ffmpeg -buildconf && \

    # nginx-rtmp
    DIR=$(mktemp -d) && cd ${DIR} && \
    curl -LOks "https://github.com/nginx/nginx/archive/release-${NGINX_VERSION}.tar.gz" && \
    tar xzvf "release-${NGINX_VERSION}.tar.gz" && \
    curl -LOks "https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/archive/v${NGINX_RTMP_VERSION}.tar.gz" && \
    tar xzvf "v${NGINX_RTMP_VERSION}.tar.gz" && \
    curl -LOks https://github.com/vozlt/nginx-module-vts/archive/master.zip && \
    unzip master.zip && \
    rm master.zip && \
    curl -LOks https://github.com/nginx/njs/archive/master.zip && \
    unzip master.zip && \
    rm master.zip && \
    cd nginx-release-${NGINX_VERSION} && \
    auto/configure \
        --with-http_ssl_module \
        --with-http_xslt_module \
        --add-module="../nginx-module-vts-master" \
        --add-module="../njs-master/nginx" \
        --add-module="../nginx-rtmp-module-${NGINX_RTMP_VERSION}" && \
    make -j"$(nproc)" && \
    make install && \
    cp ../nginx-rtmp-module-${NGINX_RTMP_VERSION}/stat.xsl /usr/local/nginx/html/info.xsl && \
    curl -LOks "https://raw.githubusercontent.com/espizo/simple-nginx-rtmp/master/www/entities.dtd" && \
    mv entities.dtd /usr/local/nginx/conf/ && \
    curl -LOks "https://raw.githubusercontent.com/espizo/simple-nginx-rtmp/master/www/xml2json.xsl" && \
    mv xml2json.xsl /usr/local/nginx/conf/ && \
    rm -rf ${DIR} && \
        
    # letsencrypt
    cd /opt && \
    git clone https://github.com/letsencrypt/letsencrypt letsencrypt && \
    letsencrypt/letsencrypt-auto --os-packages-only && \
    
    # clappr-player
    DIR=$(mktemp -d) && cd ${DIR} && \
    curl -LOks "https://github.com/clappr/clappr/archive/master.tar.gz" && \
    tar xzvf "master.tar.gz" && \
    rm master.tar.gz && \
    curl -LOks "https://github.com/clappr/clappr-level-selector-plugin/archive/master.tar.gz" && \
    tar xzvf "master.tar.gz" && \
    rm master.tar.gz && \
    mv * /usr/local/nginx/html && \
    rm -rf ${DIR} && \

    apt-get purge -y --auto-remove ${BUILDDEPS} && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/*

ADD templates /templates
ADD favicon.ico /usr/local/nginx/html/favicon.ico
ADD run.sh /run.sh
ADD snapshot.sh /snapshot.sh
RUN mkdir /usr/local/nginx/conf/vhost && \
    mkdir /usr/local/nginx/conf/vhost/www && \
    mkdir /usr/local/nginx/conf/vhost/rtmp && \
    mkdir /usr/local/nginx/html/images && \
    chmod 777 /usr/local/nginx/html/images && \
    chmod +x /run.sh && \
    chmod +x /snapshot.sh && \
    chmod 777 /snapshot.sh
    
ENV WORKER_PROCESSES=1 \
    WORKER_CONNECTIONS=1024 \
    
    RTMP_ACCESS_LOG=off \

    RTMP_SRV_PORT=1935 \
    RTMP_SRV_TIMEOUT=60s \
    RTMP_SRV_PING=3m \
    RTMP_SRV_PING_TIMEOUT=30s \
    RTMP_SRV_MAX_STREAMS=32 \
    RTMP_SRV_ACK_WINDOW=5000000 \
    RTMP_SRV_CHUNK_SIZE=4096 \
    RTMP_SRV_MAX_MESSAGE=1M \
    RTMP_SRV_BUFLEN=5s \
    
    RTMP_SRV_APP_HLS_INTERLEAVE=on \
    RTMP_SRV_APP_HLS_META=copy \
    RTMP_SRV_APP_HLS_WAIT_KEY=on \
    RTMP_SRV_APP_HLS_WAIT_VIDEO=on \
    RTMP_SRV_APP_HLS_DROP_IDLE_PUBLISHER=10s \
    RTMP_SRV_APP_HLS_SYNC=10ms \
    RTMP_SRV_APP_HLS_IDLE_STREAMS=off \
    
    RTMP_SRV_APP_HLS_HLS_FRAGMENT=2s \
    RTMP_SRV_APP_HLS_HLS_PLAYLIST_LENGTH=60 \
    RTMP_SRV_APP_HLS_HLS_SYNC=1ms \
    RTMP_SRV_APP_HLS_HLS_CONTINOUS=off \
    RTMP_SRV_APP_HLS_HLS_NESTED=off \
    RTMP_SRV_APP_HLS_HLS_CLEANUP=on \
    RTMP_SRV_APP_HLS_HLS_FRAGMENT_NAMING=sequential \
    RTMP_SRV_APP_HLS_HLS_FRAGMENT_NAMING_GRANULARITY=0 \
    RTMP_SRV_APP_HLS_HLS_FRAGMENT_SLICING=plain \
    RTMP_SRV_APP_HLS_HLS_TYPE=live \
    RTMP_SRV_APP_HLS_HLS_KEY=off \
    RTMP_SRV_APP_HLS_HLS_FRAGMENTS_PER_KEY=0 \
    
    RTMP_SRV_APP_HLS_SNAPSHOT_INTERVAL=60 \
    RTMP_SRV_APP_HLS_TRANSCODING=false \
    RTMP_SRV_APP_HLS_TRANSCODING_PROFILES=240p,360p,480p,720p,native \
    
    RTMP_PUBLISH_TOKEN=datarhei \

    HTTP_SENDFILE=on \
    HTTP_TCP_NOPUSH=on \
    HTTP_TCP_NODELAY=on \
    HTTP_ACCESS_LOG=off \

    HTTP_SRV_PORT=80 \
    HTTP_SRV_LOC_HLS_ACCESS_CONTROL_ALLOW_ORIGIN=* \
    
    HTTP_AUTH_USERNAME=admin \
    HTTP_AUTH_PASSWORD=datarhei \
    
    HTTPS_SRV=false \
    HTTPS_SRV_PORT=443 \
    HTTPS_CERT_CREATE=true \
    HTTPS_CERT_MAIL=admin@example.org \
    HTTPS_CERT_DOMAIN=example.org

CMD ["/run.sh"]
